### ISSUE TITLE
Good ideas for adding sample uses cases?

### ISSUE THREAD

**Issue by jmparikh** [cpignata/eimpact-icmp#13]
Hi all,
There's a new section for "Sample Use Case". So, I assume that we will have to add some content in there, potentially for future version -02/-03? If yes, this issue is for tracking that.

Based on what I understood, should we start off with an initial use case?
Like a small setup with some devices (all in the same Administrative Domain) where one end host pings some unreachable destination and some device replies with some extensible ICMP message, with the extension objects defined herein (such that all the devices in the path can parse the extension objects). All of this along with some supporting text to showcase the capabilities and usefulness of the metrics that were carried in the extensions in the reply.

Does this sound right? Correct me if I missed something.

**Comment by cpignata** [comment]
I feel that the "use cases" is less about how the machinery works, and more about how a user would use the feature.
See for example https://datatracker.ietf.org/doc/html/rfc4950#section-3

In other words, a *short* depiction and flow of this from the Abstract:

   The techniques presented are useful not only in a transactional
   setting (e.g., a user-issued traceroute or a ping request), but also
   in a scheduled automated setting where they may be run periodically
   in a mesh across an administrative domain to map out environmental-
   impact metrics.

@mwelzl , Ron, other thoughts?

**Comment by mwelzl** [comment]
I couldn't agree more. Perhaps the "transactional setting" is the one to start with (and maybe the only one to cover?) - just to avoid unnecessary length.

**Comment by jmparikh** [comment]
Oh okay, I got it. The use case should be a simple one but one which conveys the idea for the usage of the metrics.
Thank you @cpignata and @mwelzl, will consult the example in [RFC4950](https://datatracker.ietf.org/doc/html/rfc4950#section-3) start off with a "transactional setting" use case.
