### ISSUE TITLE
Add component throughput

### ISSUE THREAD

**Issue by mwelzl** [cpignata/eimpact-icmp#14]
We have node power, node throughput.

We have component power, but not component throughput.

Not only is this inconsistent but the same logic applies: whatever can be calculated for the node using node power and node throughput can be calculated for a component if we have both.

**Comment by cpignata** [comment]
What if components do not have throughout, like a CPU or a controller card?

**Comment by mwelzl** [comment]
Then we need to return an error message. And, that's the same about your per-component power measurements, isn't it? Sure everything must be powered but power readings may not be available. Should we open a new issue on errors?

**Comment by cpignata** [comment]
Might not be an error per se. Let’s think through the model. Maybe a bandwidth of some number or flag means not applicable. Thumb typed by Carlos Pignataro.Excuze typofraphicak errowsOn Mar 7, 2024, at 01:52, Michael Welzl ***@***.***> wrote:﻿
Then we need to return an error message. And, that's the same about your per-component power measurements, isn't it? Sure everything must be powered but power readings may not be available. Should we open a new issue on errors?

**Comment by mwelzl** [comment]
Yeah - some such message. I agree, "not applicable" sounds better than error.

**Comment by mwelzl** [comment]
or "not available".  That's maybe better - it's broader. For some components, power or throughput measurements may be "applicable" but still not "available". This gives us one notification style that would fit for everything.

**Comment by jmparikh** [comment]
I like the idea of setting a specific flag (like a sequence of bits) or just setting the bandwidth to a reversed number to convey "not applicable/available".

**Comment by cpignata** [comment]
This is awesome!!! @mwelzl , I'd just add a reference to rfc4122.
