### ISSUE TITLE
Opsdir early review by Qin Wu: 1.) make intro example list clearer

### ISSUE THREAD

**Issue by mwelzl** [cpignata/eimpact-icmp#21]
From Qin Wu's review (referring to the examplary metrics list at the end of the intro):
```
Time average, min/max seems not power metrics but time to generate metrics or
report metrics or receive metric? So the related question, how frequent should
these power metrics be reported? When should these power metrics be reported?
Does these rely on local policy or dynamic configuration?
```

Personal note from Michael: we should ensure that this list matches what's currently in the draft - e.g. geolocation is not (currently) in there.

**Comment by mwelzl** [comment]
About the "related questions":
"how frequent should these power metrics be reported?"
"When should these power metrics be reported?"
"Does these rely on local policy or dynamic configuration?"

I'm guessing that this means: how often are updates to these numbers to be calculated - e.g. if ICMP messages ask for these numbers every 1 ms, should these really invoke new system queries, and new calculations to determine an average, for example?

I wonder if this is the right spec to answer this. If we can refer to a YANG model, wouldn't this be the right place to spec. such constraints?

**Comment by cpignata** [comment]
Exactly -- this is a capability, and how frequent, etc. is up to the user of the application.
Now, since there is already someone asking, I would add a generic sentence in the "Sample Use Case" Section that says it is up to the user to figure out frequency, reporting, policy, etc etc etc
