### ISSUE TITLE
Opsdir early review by Qin Wu: 4.) terminology / draft positioning

### ISSUE THREAD

**Issue by mwelzl** [cpignata/eimpact-icmp#24]
From Qin Wu's review:
```
I think terminology lacks
consistency, e.g., in someplace we use sustainable information, in some place
we use environment impact, in
some place we use power metrics? What will be the focus of this draft? I am
wondering how to position this draft? It is related IAB
environment impact workshop, it seems also more fit into IETF since we define
protocol extensions. My suggestion is to make clear this is IETF work so choose
the right terminology can avoid ambiguity.
```

**Comment by cpignata** [comment]
Terminology versus IETF work are orthogonal.
I think we had agreed on using "environmental sustainability information" throughout. 

However, this is a valid concern and we should normalize. Remove "impact", and replace throughout based on "environmental sustainability information" (or whatever else we agree here).

**Comment by jmparikh** [comment]
Thank you, @mwelzl, for filing an issue on this!!
And I agree with @cpignata on the point on normalizing the terminology across the document to just remove any ambiguity problems and I think **environmental sustainability information** sounds just about right..
If everyone's fine, I can take this up and file a PR for addressing this issue?

**Comment by cpignata** [comment]
Sounds good, @jmparikh , please do!
