### ISSUE TITLE
Opsdir early review by Qin Wu: 5.) definition / references for EERC numbers

### ISSUE THREAD

**Issue by mwelzl** [cpignata/eimpact-icmp#25]
From Qin Wu's review:
```
Can you provide definition for
EERC numbers and also provide reference, can you also provide referenced
document or specification for the following three terms: a.  ISO 14001:2015 b.
TCO Certified c.  Energy-efficient ethernet
```

**Comment by cpignata** [comment]
Unfortunately there is no global standard to our knowledge. If more are needed, can be specified as already clarified:
_"EERC numbers are assignable on a first-come-first-serve (FCFS) basis."_

**Comment by mwelzl** [comment]
Yes but we should add references for the three items here. I can do this.
The first: https://www.iso.org/standard/60857.html   and how to cite: https://www.reagent.co.uk/blog/how-to-reference-an-iso-standard/#how_to_reference_an_iso_standard
The second: https://tcocertified.com/
The third: probably this?  https://standards.ieee.org/ieee/802.3az/4270/

**Comment by cpignata** [comment]
I agree and great call out, @mwelzl ! 
In fact, I think we should also require in the IANA section for a reference for new registrations.

**Comment by cpignata** [comment]
Like OLD:
   EERC numbers are assignable on a first-come-first-serve (FCFS) basis.
NEW:
   EERC numbers are assignable on a first-come-first-serve (FCFS) basis, and require a reference to the definition of the certification.
