### ISSUE TITLE
How to convey "power" when there's a YANG model

### ISSUE THREAD

**Issue by mwelzl** [cpignata/eimpact-icmp#3]
My suggestion would be to at least add "linecard idle power consumption" as an object per linecard per router, because this is probably what was used in [x], and then also add a citation to [x] to give an example of how this could be used.

[x] https://arxiv.org/pdf/2306.00726.pdf
https://www.computer.org/csdl/proceedings-article/lcn/2023/10223344/1QdFTbKvNio

**Comment by jmparikh** [comment]
Thanks for looking into this @cpignata !

I just had posted the entire sub-object along with the headers.
Ooppss yes you're right! I totally missed that the length in the object header is including the header and the payload. Thanks for removing that! And sorry for missing that. Adding an extra length field is surely not required.

Option 4 also sounds like a good idea, like power from just one component.. Cause option 3 or 4, shouldn't be that big of a difference I feel. It's just that we will be utilizing the entire capacity of the length field by allowing power from multiple components.

**Comment by cpignata** [comment]
Awesome!
